/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeemci;

import java.awt.Color;
import javafx.scene.layout.Background;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author LOSSENI SANGARE
 */
public class ACCUEIL extends javax.swing.JFrame {
String utilisateur;
int id_user;
    /**
     * Creates new form ACCUEIL
     */ 
    int panSelection=0;
    public ACCUEIL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        panel_option = new javax.swing.JPanel();
        new_btn = new javax.swing.JButton();
        liste_btn = new javax.swing.JButton();
        statut = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filleul_btn = new javax.swing.JButton();
        parrain_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        new_btn1 = new javax.swing.JButton();
        new_btn2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(null);

        panel_option.setForeground(new java.awt.Color(51, 0, 51));

        new_btn.setBackground(new java.awt.Color(153, 255, 255));
        new_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_btn.setText("Nouveau");
        new_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        new_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btnActionPerformed(evt);
            }
        });

        liste_btn.setBackground(java.awt.Color.cyan);
        liste_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        liste_btn.setText("voir liste");
        liste_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        liste_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                liste_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                liste_btnMouseExited(evt);
            }
        });
        liste_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liste_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_optionLayout = new javax.swing.GroupLayout(panel_option);
        panel_option.setLayout(panel_optionLayout);
        panel_optionLayout.setHorizontalGroup(
            panel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(liste_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(new_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_optionLayout.setVerticalGroup(
            panel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_optionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_optionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liste_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(panel_option);
        panel_option.setBounds(70, 410, 490, 60);
        jPanel4.add(statut);
        statut.setBounds(276, 399, 118, 0);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        filleul_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        filleul_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture d’écran (89).png"))); // NOI18N
        filleul_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filleul_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                filleul_btnMouseExited(evt);
            }
        });
        filleul_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filleul_btnActionPerformed(evt);
            }
        });

        parrain_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        parrain_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture d’écran (87).png"))); // NOI18N
        parrain_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parrain_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parrain_btnMouseExited(evt);
            }
        });
        parrain_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parrain_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(parrain_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filleul_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filleul_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parrain_btn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(40, 240, 580, 140);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        new_btn1.setBackground(new java.awt.Color(0, 153, 153));
        new_btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FILLEUL parrain.png"))); // NOI18N
        new_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_btn1MouseExited(evt);
            }
        });
        new_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btn1ActionPerformed(evt);
            }
        });

        new_btn2.setBackground(new java.awt.Color(0, 153, 153));
        new_btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture d’écran (84).png"))); // NOI18N
        new_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_btn2MouseExited(evt);
            }
        });
        new_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(new_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(new_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(new_btn1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(630, 280, 310, 220);

        jButton14.setBackground(new java.awt.Color(0, 204, 153));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sfa.jpg"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14);
        jButton14.setBounds(50, 10, 100, 90);

        jButton6.setBackground(new java.awt.Color(0, 204, 153));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AEEMCI_1.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(870, 10, 100, 80);

        jButton16.setBackground(new java.awt.Color(0, 204, 153));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deconecte.jpg"))); // NOI18N
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton16MouseExited(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);
        jButton16.setBounds(890, 650, 60, 60);

        jButton13.setBackground(new java.awt.Color(0, 204, 153));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/quitter.jpg"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton13MouseExited(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(100, 650, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/conecte.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(220, 120, 35, 40);

        user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(0, 153, 0));
        jPanel4.add(user);
        user.setBounds(240, 170, 170, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("connecté :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(160, 170, 72, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture d’écran (83).png"))); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(-90, 0, 1080, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void parrain_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parrain_btnActionPerformed
        // TODO add your handling code here:
          liste_btn.setText("liste parrain");
          liste_btn.setBackground(Color.cyan);
          new_btn.setBackground(Color.CYAN);
        new_btn.setText("nouveau parrain");
        panel_option.setVisible(true);
         liste_btn.setVisible(true);
        new_btn.setVisible(true);
        statut.setText("parrain");
     
    }//GEN-LAST:event_parrain_btnActionPerformed

    private void new_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btnActionPerformed
        // TODO add your handling code here:
        String statuts=statut.getText();
        ENREGISTREMENT nouveau =new ENREGISTREMENT();
        nouveau.setPersonne(statuts.toUpperCase());
        nouveau.setId(id_user);
        nouveau.setUser(utilisateur);
        nouveau.setVisible(true);
        dispose();
    }//GEN-LAST:event_new_btnActionPerformed

    private void liste_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liste_btnActionPerformed
        // TODO add your handling code here:
        liste list =new liste();
     list.setId(id_user);
        list.setUser(utilisateur);

        list.setVisible(true);
        if (liste_btn.getText()=="liste filleul"){
        list.setSelection(0);
        }else if(liste_btn.getText()=="liste parrain"){
            list.setSelection(1);
        }
        dispose();
    }//GEN-LAST:event_liste_btnActionPerformed

    private void filleul_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filleul_btnActionPerformed
        // TODO add your handling code here:
        liste_btn.setText("liste filleul");
        new_btn.setText("nouveau filleul");
        liste_btn.setBackground(Color.pink);
          new_btn.setBackground(Color.PINK);
        panel_option.setVisible(true);
        statut.setText("etudiant");
        
    }//GEN-LAST:event_filleul_btnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        parrain_btn.setBackground(Color.cyan);
        filleul_btn.setBackground(Color.pink);
        panel_option.setVisible(false);
        statut.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
          panel_option.setVisible(false);
      
    }//GEN-LAST:event_formMouseReleased

    public void setUser(String user){
        utilisateur= user;
    }
    
    public void setId(int id){
        id_user =id;
    }
    private void new_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btn1ActionPerformed
        // TODO add your handling code here:
       liste liste =new liste();
       liste.setSelection(2);
       liste.setId(id_user);
       liste.setUser(utilisateur);

       liste.setVisible(true);
       
       dispose();
    }//GEN-LAST:event_new_btn1ActionPerformed

    private void new_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_btn2ActionPerformed
        // TODO add your handling code here:
        PARRAINER parrainage =new PARRAINER();
        parrainage.setId(id_user);
        parrainage.setUser(utilisateur);
        parrainage.setVisible(true);
        dispose();
    }//GEN-LAST:event_new_btn2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        CONNECTER con =new CONNECTER();
        con.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        user.setText(utilisateur);
       // JOptionPane.showMessageDialog(null, utilisateur+" -- "+id_user);
            }//GEN-LAST:event_formWindowOpened

    private void filleul_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filleul_btnMouseExited
        // TODO add your handling code here:
         filleul_btn.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_filleul_btnMouseExited

    private void liste_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_btnMouseExited
        // TODO add your handling code here:
       /* if("liste filleul".equals(liste_btn.getText())){
         liste_btn.setBackground(new java.awt.Color(225,204,204));
           }else{
          liste_btn.setBackground(new java.awt.Color(153,255,255));
        }*/
    }//GEN-LAST:event_liste_btnMouseExited

    private void liste_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liste_btnMouseEntered
        // TODO add your handling code here:
       
        //  liste_btn.setBackground(new java.awt.Color(225,22,223));
      
    }//GEN-LAST:event_liste_btnMouseEntered

    private void filleul_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filleul_btnMouseEntered
        // TODO add your handling code here:
         filleul_btn.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_filleul_btnMouseEntered

    private void parrain_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parrain_btnMouseEntered
        // TODO add your handling code here:
          parrain_btn.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_parrain_btnMouseEntered

    private void parrain_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parrain_btnMouseExited
        // TODO add your handling code here:
    parrain_btn.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_parrain_btnMouseExited

    private void new_btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_btn2MouseExited
        // TODO add your handling code here:
        new_btn2.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_new_btn2MouseExited

    private void new_btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_btn2MouseEntered
        // TODO add your handling code here:
        new_btn2.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_new_btn2MouseEntered

    private void new_btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_btn1MouseEntered
        // TODO add your handling code here:
        new_btn1.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_new_btn1MouseEntered

    private void new_btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_btn1MouseExited
        // TODO add your handling code here:
        new_btn1.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_new_btn1MouseExited

    private void jButton16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseExited
        // TODO add your handling code here:
        jButton16.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton16MouseExited

    private void jButton16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseEntered
        // TODO add your handling code here:
        jButton16.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton16MouseEntered

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseExited
        // TODO add your handling code here:
        jButton13.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton13MouseExited

    private void jButton13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseEntered
        // TODO add your handling code here:
        jButton13.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton13MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACCUEIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACCUEIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACCUEIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACCUEIL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACCUEIL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filleul_btn;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton liste_btn;
    private javax.swing.JButton new_btn;
    private javax.swing.JButton new_btn1;
    private javax.swing.JButton new_btn2;
    private javax.swing.JPanel panel_option;
    private javax.swing.JButton parrain_btn;
    private javax.swing.JLabel statut;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
