/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeemci;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author LOSSENI SANGARE
 */
public class ENREGISTREMENT extends javax.swing.JFrame {

    /**
     * Creates new form ENREGISTREMENT
     */
    Statement stmt;
    connexionBd maConnexion =new connexionBd();
    String utilisateur;
int id_user;
    public ENREGISTREMENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NCE_TXT = new javax.swing.JTextField();
        NOM_TXT = new javax.swing.JTextField();
        PRENOM_TXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SEXE_BOX = new javax.swing.JComboBox();
        SPECIALITE_BOX = new javax.swing.JComboBox();
        NIVEAU_BOX = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cell_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PERSONNE_fl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 204, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/retour_1.jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(590, 350, 50, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NCE_TXT.setBackground(new java.awt.Color(204, 255, 255));
        NCE_TXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        NOM_TXT.setBackground(new java.awt.Color(204, 255, 255));
        NOM_TXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        PRENOM_TXT.setBackground(new java.awt.Color(204, 255, 255));
        PRENOM_TXT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel2.setText("PRENOM");

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel3.setText("NCE");

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel4.setText("NOM");

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel5.setText("SEXE");

        SEXE_BOX.setBackground(new java.awt.Color(153, 255, 255));
        SEXE_BOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MASCULIN", "FEMININ" }));

        SPECIALITE_BOX.setBackground(new java.awt.Color(153, 255, 255));
        SPECIALITE_BOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SPECIALITE" }));

        NIVEAU_BOX.setBackground(new java.awt.Color(153, 255, 255));
        NIVEAU_BOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIVEAU" }));
        NIVEAU_BOX.setName("grade_box"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel7.setText("FILIERE");

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel6.setText("CELL");

        cell_txt.setBackground(new java.awt.Color(204, 255, 255));
        cell_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cell_txt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NOM_TXT)
                                .addComponent(NCE_TXT, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                                .addComponent(SEXE_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PRENOM_TXT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NIVEAU_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(SPECIALITE_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCE_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOM_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRENOM_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEXE_BOX, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cell_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SPECIALITE_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIVEAU_BOX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(50, 80, 520, 238);

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ENREGISTREMENT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(47, 6, 312, 58);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/confirmer1.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 360, 60, 40);

        PERSONNE_fl.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        PERSONNE_fl.setForeground(new java.awt.Color(0, 102, 102));
        PERSONNE_fl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PERSONNE_fl.setLabelFor(this);
        PERSONNE_fl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(PERSONNE_fl);
        PERSONNE_fl.setBounds(360, 10, 190, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FOND.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 10, 630, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void setUser(String user){
        utilisateur= user;
    }
   
    public void setId(int id){
        id_user =id;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        String spe=SPECIALITE_BOX.getSelectedItem().toString();
        String parcours;
        if("MATHEMATIQUE".equals(spe) || "GENIE INFORMATIQUE".equals(spe) || "INFORMATIQUE".equals(spe)
                ||"MIAGE".equals(spe) || "MATHS INFO".equals(spe)){
            parcours="MATHS INFO";
        }else if("CHIMIE".equals(spe) || "PHYSIQUE".equals(spe) || "PHYSIQUE-CHIMIE".equals(spe)){
        parcours="PHYSIQUE CHIMIE";
        }else{
            parcours="SN";
     }
        String nce = NCE_TXT.getText();
        String nom =NOM_TXT.getText();
        String prenom = PRENOM_TXT.getText();
        String cell=cell_txt.getText();
        String sexe = SEXE_BOX.getSelectedItem().toString();
        String statut = PERSONNE_fl.getText().toLowerCase();
        String filiere= SPECIALITE_BOX.getSelectedItem().toString();
        String niveau = NIVEAU_BOX.getSelectedItem().toString();
        String parrainer = "NON"; 
        String sql="";
        
        if(nom.contains("'") || prenom.contains("'") || nce.contains("'")){
            nom = nom.replaceAll("'","''");
           // prenom = prenom.replaceAll("'", "''");
            JOptionPane.showMessageDialog(null, "Pour plus de securité, veuillez enlever l'apostrophe: '' ' '' ");
        }else{
        
         int entier,nbre=0;
         
         
         
         for(int i=0;i<cell.length();i++){
             for(int j=0;j<=9;j++){
                 char mot=cell.charAt(i);
              
                 
                 entier=Character.getNumericValue(mot);
                 if(j==entier){
                     nbre+=1;
                     }
             }
         }
         
         if(nbre==8 && cell.length()==8 ){
            
       if("etudiant".equals(statut)){
             sql ="INSERT INTO "+statut+"(nce_et,nom_et,prenom_et,sexe,filiere_et,niveau_et,telephone_et,parrainer,parrainer_2)"
                    + " VALUE('"+nce+"','"+nom+"','"+prenom+"','"+sexe+"','"+filiere+"','"+niveau+"','"+cell+"','"+parrainer+"','"+parrainer+"')";
        }else {
              
           sql ="INSERT INTO "+statut+"(nce_par,nom_par,prenom_par,sexe,parcours,filiere_par,niveau_par,telephone_par,parrain_ok,parrain2_ok)"
            + " VALUE('"+nce+"','"+nom+"','"+prenom+"','"+sexe+"','"+parcours+"','"+filiere+"','"+niveau+"','"+cell+"','"+parrainer+"','"+parrainer+"')";
       }
       
        try {
            stmt= maConnexion.ObtenirConnexion().createStatement();
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, statut+": "+nom+" "+prenom+" ENREGISTRER AVEC SUCCES !!!");
            NCE_TXT.setText("");
            NOM_TXT.setText("");
            PRENOM_TXT.setText("");
            cell_txt.setText("");
            SEXE_BOX.setSelectedIndex(0);
            SPECIALITE_BOX.setSelectedIndex(0);
            NIVEAU_BOX.setSelectedIndex(0);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "VEILLEZ BIEN REMPLIR TOUS LES CHAMPS"+ex);
        }
         }else{
             JOptionPane.showMessageDialog(null, "SAISSISEZ UN BON NUMERO CELLULAIRE");
         }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        NIVEAU_BOX.removeAllItems();
        SPECIALITE_BOX.removeAllItems();
        NIVEAU_BOX.addItem("NIVEAU");
        SPECIALITE_BOX.addItem("SPECIALITE");
      //  NIVEAU_BOX.rem
        String sql ="SELECT * FROM grade";
        String sql2 ="SELECT * FROM specialite";
        try {
            stmt = maConnexion.ObtenirConnexion().createStatement();
            ResultSet resultat =stmt.executeQuery(sql);
            while(resultat.next()){
                NIVEAU_BOX.addItem(resultat.getString("niveau"));
            }
            resultat.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERREUR "+ex);
        }
        
        try {
         stmt= maConnexion.ObtenirConnexion().createStatement();
         ResultSet resultat2 = stmt.executeQuery(sql2);
         while(resultat2.next()){
             SPECIALITE_BOX.addItem(resultat2.getString("filiere"));
         }
         resultat2.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:.
        ACCUEIL accueil =new  ACCUEIL();
                accueil.setVisible(true);
                accueil.setId(id_user);
                accueil.setUser(utilisateur);
                dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ENREGISTREMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ENREGISTREMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ENREGISTREMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ENREGISTREMENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ENREGISTREMENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NCE_TXT;
    private javax.swing.JComboBox NIVEAU_BOX;
    private javax.swing.JTextField NOM_TXT;
    private javax.swing.JLabel PERSONNE_fl;
    private javax.swing.JTextField PRENOM_TXT;
    private javax.swing.JComboBox SEXE_BOX;
    private javax.swing.JComboBox SPECIALITE_BOX;
    private javax.swing.JTextField cell_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

public String setPersonne(String statut){
        PERSONNE_fl.setText(statut);
        return null;
}
}
