/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeemci;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.Timer;
/**
 *
 * @author LOSSENI SANGARE
 */
public class PARRAINER extends javax.swing.JFrame {

    /**
     * Creates new form PARRAINER
     */
    String utilisateur;
    int id_user;
    connexionBd maConnexion =new connexionBd();
    Statement stmt;
            ArrayList tab =new ArrayList();
        ArrayList tab_nom =new ArrayList();
        
         ArrayList tab2 =new ArrayList();
        ArrayList tab2_nom =new ArrayList();
          int taille_tab=0;
           String temps= new String();
           int indice;
           int nbre_parrain=0,nbre_parrain2=0;
           String apli_encour="NON",is_tab1="OUI";
           String sexe;
          String trouv_parrain ="NON";
      
    public PARRAINER() {
        initComponents();
    }

    /*
        public class progresso implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            int n=jProgressBar1.getValue();
            String label="";
            if(n<100){
                n++;
                label=label.valueOf(n)+"%";
                jProgressBar1.setValue(n);
                prog_lbl.setText(label);
            }else{
                timer.stop();
               
            }
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_et = new javax.swing.JTable();
        sexe_box = new javax.swing.JComboBox();
        filiere_box = new javax.swing.JComboBox();
        nce_lbl = new javax.swing.JLabel();
        nom_parrain_lbl = new javax.swing.JPanel();
        parrain_lbl = new javax.swing.JLabel();
        panel_btn = new javax.swing.JPanel();
        recherche_btn = new javax.swing.JButton();
        attribuer_btn = new javax.swing.JButton();
        bar_lbl = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        user_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prog_lbl = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 150));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setName(""); // NOI18N

        Table_et.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Table_et.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NCE", "NOM", "PRENOM", "NUMERO"
            }
        ));
        Table_et.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Table_et.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_etMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_et);

        sexe_box.setBackground(new java.awt.Color(0, 255, 204));
        sexe_box.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sexe_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEXE", "MASCULIN", "FEMININ", "TOUT LE MONDE" }));
        sexe_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexe_boxActionPerformed(evt);
            }
        });

        filiere_box.setBackground(new java.awt.Color(0, 255, 204));
        filiere_box.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        filiere_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FILIERE", "MATHS INFO", "PHYSIQUE CHIMIE", "SN" }));
        filiere_box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filiere_boxItemStateChanged(evt);
            }
        });
        filiere_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filiere_boxActionPerformed(evt);
            }
        });

        nce_lbl.setText("NCE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(sexe_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73)
                        .addComponent(filiere_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nce_lbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filiere_box)
                    .addComponent(sexe_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nce_lbl)
                .addGap(129, 129, 129))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 170, 530, 480);

        nom_parrain_lbl.setBackground(new java.awt.Color(204, 255, 255));

        parrain_lbl.setBackground(new java.awt.Color(0, 0, 51));
        parrain_lbl.setFont(new java.awt.Font("Algerian", 1, 25)); // NOI18N
        parrain_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout nom_parrain_lblLayout = new javax.swing.GroupLayout(nom_parrain_lbl);
        nom_parrain_lbl.setLayout(nom_parrain_lblLayout);
        nom_parrain_lblLayout.setHorizontalGroup(
            nom_parrain_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_parrain_lblLayout.createSequentialGroup()
                .addComponent(parrain_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        nom_parrain_lblLayout.setVerticalGroup(
            nom_parrain_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nom_parrain_lblLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parrain_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.add(nom_parrain_lbl);
        nom_parrain_lbl.setBounds(560, 250, 500, 80);

        panel_btn.setBackground(new java.awt.Color(0, 0, 51));
        panel_btn.setForeground(new java.awt.Color(0, 0, 51));
        panel_btn.setLayout(null);

        recherche_btn.setBackground(new java.awt.Color(51, 102, 255));
        recherche_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recherche_btn.setForeground(new java.awt.Color(255, 255, 255));
        recherche_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vision1.jpg"))); // NOI18N
        recherche_btn.setText("RECHERCHER");
        recherche_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_btnActionPerformed(evt);
            }
        });
        panel_btn.add(recherche_btn);
        recherche_btn.setBounds(10, 10, 200, 50);

        attribuer_btn.setBackground(new java.awt.Color(102, 255, 255));
        attribuer_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        attribuer_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/confirmer.jpg"))); // NOI18N
        attribuer_btn.setText("ATTRIBUER");
        attribuer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attribuer_btnActionPerformed(evt);
            }
        });
        panel_btn.add(attribuer_btn);
        attribuer_btn.setBounds(10, 79, 200, 50);

        jPanel3.add(panel_btn);
        panel_btn.setBounds(650, 390, 220, 140);
        jPanel3.add(bar_lbl);
        bar_lbl.setBounds(720, 150, 51, 0);

        jButton12.setBackground(new java.awt.Color(0, 204, 153));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/quitter.jpg"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12);
        jButton12.setBounds(60, 670, 60, 60);

        jButton11.setBackground(new java.awt.Color(0, 204, 153));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sfa.jpg"))); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(0, 0, 70, 60);

        jButton4.setBackground(new java.awt.Color(0, 204, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/retour_1.jpg"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(880, 670, 70, 60);

        jButton6.setBackground(new java.awt.Color(0, 204, 153));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AEEMCI_1.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(930, 0, 90, 70);

        jButton17.setBackground(new java.awt.Color(0, 204, 153));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/impression_1.jpg"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton17);
        jButton17.setBounds(530, 670, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/conecte.jpg"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(510, 100, 30, 40);

        user_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user_lbl.setForeground(new java.awt.Color(0, 153, 0));
        jPanel3.add(user_lbl);
        user_lbl.setBounds(540, 140, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("connecté :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(460, 140, 72, 20);

        prog_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prog_lbl.setForeground(new java.awt.Color(0, 0, 204));
        jPanel3.add(prog_lbl);
        prog_lbl.setBounds(920, 120, 60, 20);

        jProgressBar1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(jProgressBar1);
        jProgressBar1.setBounds(600, 230, 380, 30);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 18)); // NOI18N
        jLabel1.setText("recherche parrain..............");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(580, 210, 270, 22);

        lab.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 30)); // NOI18N
        jPanel3.add(lab);
        lab.setBounds(850, 210, 120, 20);

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("PARRAIN");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(710, 170, 190, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Capture d’écran (92).png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(-70, 0, 1140, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(692, 692, 692)
                .addComponent(jLabel3))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

public void setUser(String user){
    utilisateur=user;
}    
    public void setId(int id){
        id_user = id;
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        nce_lbl.setVisible(false);
        
        
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   jProgressBar1.setVisible(false);
   jLabel5.setVisible(false);
  lab.setVisible(false);
  jLabel1.setVisible(false);
  
        ActionEvent ev = null;
        timer = new Timer(30, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int n = jProgressBar1.getValue();
                if (n < 100) {
                    n=n+2;
                    jProgressBar1.setValue(n);
                    lab.setText(n+ "%");
                } else {
                    timer.stop();
                    jProgressBar1.setVisible(false);
                    lab.setVisible(false);
                  jLabel1.setVisible(false);
                    
                   // jButton1.setVisible(false);
                   // jLabel1.setVisible(true);
                    nom_parrain_lbl.setVisible(true);
                    jLabel5.setVisible(true);
                 }
            }
        });
        
// TODO add your handling code here:
         // timer =new Timer(3, new progresso());
        user_lbl.setText(utilisateur);
     //   jProgressBar1.setVisible(false);
        nom_parrain_lbl.setVisible(false);
        jLabel5.setVisible(false);
        nce_lbl.setVisible(false);
       nom_parrain_lbl.setBackground(Color.LIGHT_GRAY);
       parrain_lbl.setBackground(Color.gray);
       recherche_btn.setEnabled(false);
       attribuer_btn.setEnabled(false);
        int cal =Calendar.getInstance().getWeekYear();
       
        temps=String.valueOf(cal);
      /* String titre= titre_lbl.getText()+" "+temps;
        titre_lbl.setText(titre);
      */
    }//GEN-LAST:event_formWindowOpened

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:.
        ACCUEIL ACC = new ACCUEIL();
        ACC.setVisible(true);
        ACC.setId(id_user);
        ACC.setUser(utilisateur);

        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void attribuer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attribuer_btnActionPerformed
        // TODO add your handling code here:
        String NCE_et = nce_lbl.getText();
        String NCE_par =tab.get(indice).toString();
        int cal =Calendar.getInstance().getWeekYear();
        String temp= new String();
        temp=String.valueOf(cal);
        String parrain = parrain_lbl.getText();
        String filleul = Table_et.getValueAt(Table_et.getSelectedRow(),1).toString()+" "+
        Table_et.getValueAt(Table_et.getSelectedRow(), 2).toString();

        String req="INSERT INTO attribuer (nce_et,nce_par,annee,utilisateur)VALUE ('"+NCE_et+"','"+NCE_par+"','"+temp+"','"+id_user+"')";
        try {
            stmt.executeUpdate(req);

            String parrainer2="OUI";

            String req1="UPDATE etudiant SET parrainer='"+parrainer2+"'WHERE nce_et='"+NCE_et+"'";
            //        String req2=""
            try {
                Statement stmt2 =maConnexion.ObtenirConnexion().createStatement();
                stmt2.executeUpdate(req1);
              //  JOptionPane.showMessageDialog(null, "ETUDION PARRAINER");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                Logger.getLogger(PARRAINER.class.getName()).log(Level.SEVERE, null, ex);
            }
            String parrainer3="OUI";
            String req2;
            if("OUI".equals(is_tab1)){
                req2="UPDATE parrain SET parrain_ok ='"+parrainer3+"' WHERE nce_par='"+NCE_par+"'";
            }else{
                req2="UPDATE parrain SET parrain2_ok ='"+parrainer3+"' WHERE nce_par='"+NCE_par+"'";
            }

            try {
                Statement stmt3 =maConnexion.ObtenirConnexion().createStatement();
                stmt3.executeUpdate(req2);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

            JOptionPane.showMessageDialog(null, parrain+" EST DESORMAIS LE PARRAIN DE "+filleul);
            tab.remove(indice);
            tab_nom.remove(indice);
            if("OUI".equals(is_tab1)&&tab.isEmpty()){
                is_tab1="NON";
            }else if("OUI".equals(is_tab1)&& !tab.isEmpty()){
                is_tab1="OUI";
            }else if("NON".equals(is_tab1)){
                is_tab1="NON";
            }
            recherche_btn.setEnabled(false);
            attribuer_btn.setEnabled(false);
            int taille=filiere_box.getSelectedIndex();
            filiere_box.setSelectedIndex(taille);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_attribuer_btnActionPerformed

    private void recherche_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_btnActionPerformed
 jProgressBar1.setVisible(true);
  lab.setVisible(true);
  jLabel1.setVisible(true);
  jProgressBar1.setValue(0);
      // jLabel1.setVisible(false); 
  jLabel5.setVisible(false);
nom_parrain_lbl.setVisible(false);
//prog_lbl.setText("0%");
  
         timer.start();
        
        ///*******************REMPLISSAGE DES DEUX TABLEAUX**********************************************
   // jProgressBar1.setVisible(true);
      //  jProgressBar1.setValue(0);
    //prog_lbl.setText("0%");
  

        //jProgressBar1.setValue(100);
      
        try {
             //nom_parrain_lbl.setVisible(true);
            String type_sexe=sexe_box.getSelectedItem().toString();
            String parcours =filiere_box.getSelectedItem().toString();

            if("NON".equals(apli_encour)){
                tab.clear();
                tab2.clear();
                tab_nom.clear();
                tab2_nom.clear();

                taille_tab=0;

                String parrain="NON";
                String parrain2="NON";

                String req;
                if("TOUT LE MONDE".equals(sexe_box.getSelectedItem().toString())){
                    req="SELECT * FROM parrain WHERE parrain_ok='"+parrain+"'AND parcours='"+parcours+"' ";
                }else{
                    req="SELECT * FROM parrain WHERE parrain_ok='"+parrain+"'AND parcours='"+parcours+"' AND sexe ='"+type_sexe+"'";
                }

                String nom ;

                try {
                    Statement stmt5=maConnexion.ObtenirConnexion().createStatement();
                    try (ResultSet res = stmt5.executeQuery(req)) {
                        while(res.next()){
                            tab.add(res.getString("nce_par"));
                            nom = res.getString("nom_par")+" "+res.getString("prenom_par");
                            tab_nom.add(nom);
                            taille_tab +=1;
                        }
                        nbre_parrain=taille_tab;
                        if(nbre_parrain==0){
                            is_tab1="NON";
                            trouv_parrain="NON";
                        }else{
                            is_tab1="OUI";
                            trouv_parrain="OUI";
                        }
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null ,e);
                }

                String req3;
                if("TOUT LE MONDE".equals(sexe_box.getSelectedItem().toString())){
                    req3=req3="SELECT * FROM parrain WHERE parrain2_ok='"+parrain2+"' AND parcours='"+parcours+"'";
                }else{
                    req3="SELECT * FROM parrain WHERE parrain2_ok='"+parrain2+"' AND parcours='"+parcours+"'AND sexe ='"+type_sexe+"'";
                }
                Statement stmt4;
                try {
                    stmt4 = maConnexion.ObtenirConnexion().createStatement();
                    ResultSet res2 =stmt4.executeQuery(req3);
                    String nom2;
                    while(res2.next()){
                        tab2.add(res2.getString("nce_par"));
                        nom2 =res2.getString("nom_par")+" "+res2.getString("prenom_par");
                        tab2_nom.add(nom2);
                        nbre_parrain2+=1;
                    }

                    ///////////////......\\\\\\\\\\\\\\\\\\\\\\\\\\\

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                    //ogger.getLogger(PARRAINER.class.getName()).log(Level.SEVERE, null, ex);
                }

                apli_encour="OUI";

            }

            ///////////////CHOIX ALEATOIRE DU PARRAIN\\\\\\\\\\\\\\\\\\\\

            if(!tab.isEmpty()){

                nom_parrain_lbl.setBackground(Color.CYAN);
                parrain_lbl.setForeground(Color.black);

                int nbre_aleatoire = (int)(Math.random()*taille_tab);
                indice=nbre_aleatoire;
                parrain_lbl.setText(tab_nom.get(nbre_aleatoire).toString());
                attribuer_btn.setEnabled(true);
                apli_encour ="OUI";

            }else if(tab.isEmpty() && !tab2.isEmpty() ){
                int reponse=  JOptionPane.showConfirmDialog(null, "TOUS LES PARRAINS ONT AU MOINS UN FILLEUL VOULLEZ-VOUS LEURS ATTRIBUER UN SECOND FILLEUL ?");
                if(reponse==JOptionPane.YES_OPTION){
                    try {
                        tab=tab2;
                        taille_tab=tab.size();
                        tab_nom =tab2_nom;
                        is_tab1="NON";
                        recherche_btn.doClick();

                        //nom_parrain_lbl.setEnabled(true);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, tab.size()+".../"+ e);
                    }

                }

            }else if(tab.isEmpty() && tab2.isEmpty()&& "OUI".equals(trouv_parrain)){
                JOptionPane.showMessageDialog(null,"TOUS LES PARRAINS SONT MAINTENANT OCCUPES");

            }else if(tab.isEmpty() && tab2.isEmpty()&& "NON".equals(trouv_parrain)){
                JOptionPane.showMessageDialog(null,"PAS DE PARRAIN DISPONIBLE POUR CE CHOIX");
            }

        } catch (Exception e) {
        }
          /////*************************************************************
    }//GEN-LAST:event_recherche_btnActionPerformed

    private void filiere_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filiere_boxActionPerformed
        // TODO add your handling code here:
        nom_parrain_lbl.setVisible(false);
        jLabel5.setVisible(false);
       // jProgressBar1.setVisible(false);
        apli_encour="NON";
        tab.clear();
        tab_nom.clear();
        tab2.clear();
        tab2_nom.clear();

        nom_parrain_lbl.setBackground(Color.LIGHT_GRAY);
        parrain_lbl.setText(null);
        recherche_btn.setEnabled(false);
        attribuer_btn.setEnabled(false);
        String sql;
        String parrainer="NON";
        String sexe=sexe_box.getSelectedItem().toString();
        String filiere = filiere_box.getSelectedItem().toString();
        DefaultTableModel model =new DefaultTableModel();
        model.addColumn("NCE");
        model.addColumn("NOM");
        model.addColumn("PRENOM");
        model.addColumn("NUMERO");
        Table_et.setModel(model);

        if("SEXE".equals(sexe_box.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "champ sexe non Selectionné");
        }else{

            if("TOUT LE MONDE".equals(sexe_box.getSelectedItem().toString())){
                sql="SELECT * FROM etudiant WHERE filiere_et='"+filiere+"' AND parrainer='"+parrainer+"'ORDER BY nom_et";

            }else{

                sql="SELECT * FROM etudiant WHERE sexe='"+sexe+"' AND filiere_et='"+filiere+"' AND parrainer='"+parrainer+"'ORDER BY nom_et";
            }
            try {
                stmt=maConnexion.ObtenirConnexion().createStatement();
                ResultSet res = stmt.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{res.getString("nce_et"),res.getString("nom_et"),res.getString("prenom_et"),
                        res.getString("telephone_et")});
            }
            res.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERREUR : "+ex);
        }

        }

    }//GEN-LAST:event_filiere_boxActionPerformed

    private void filiere_boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filiere_boxItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_filiere_boxItemStateChanged

    private void sexe_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexe_boxActionPerformed
        // TODO add your handling code here:
        apli_encour="NON";
        tab.clear();
        tab_nom.clear();
        tab2.clear();
        tab2_nom.clear();
        int taille=filiere_box.getSelectedIndex();
        filiere_box.setSelectedIndex(taille);

    }//GEN-LAST:event_sexe_boxActionPerformed

    private void Table_etMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_etMouseClicked
        // TODO add your handling code here:
     //   jProgressBar1.setVisible(false);
      nom_parrain_lbl.setVisible(false);
      jLabel5.setVisible(false);
        nce_lbl.setText(Table_et.getValueAt(Table_et.getSelectedRow(), 0).toString());
        nom_parrain_lbl.setBackground(Color.lightGray);
        parrain_lbl.setText(null);
        recherche_btn.setEnabled(true);
        attribuer_btn.setEnabled(false);

    }//GEN-LAST:event_Table_etMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
         Font font = new Font("Courier",Font.PLAIN,10);
       Table_et.setFont(font);
         MessageFormat header = new MessageFormat("LISTES DES FILLEULS");
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        
        try{
            Table_et.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(java.awt.print.PrinterException e){
            JOptionPane.showMessageDialog(null, "ERREUR IMPRESSION "+e.getMessage());
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        // TODO add your handling code here:
        jButton12.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton12MouseExited

    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        // TODO add your handling code here:
        jButton12.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton12MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        // TODO add your handling code here:
         jButton11.setBackground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        // TODO add your handling code here:
        jButton11.setBackground(new java.awt.Color(153,102,255));
    }//GEN-LAST:event_jButton11MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PARRAINER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PARRAINER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PARRAINER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PARRAINER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PARRAINER().setVisible(true);
            }
        });
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_et;
    private javax.swing.JButton attribuer_btn;
    public static javax.swing.JLabel bar_lbl;
    private javax.swing.JComboBox filiere_box;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab;
    private javax.swing.JLabel nce_lbl;
    private javax.swing.JPanel nom_parrain_lbl;
    private javax.swing.JPanel panel_btn;
    private javax.swing.JLabel parrain_lbl;
    private javax.swing.JLabel prog_lbl;
    private javax.swing.JButton recherche_btn;
    private javax.swing.JComboBox sexe_box;
    private javax.swing.JLabel user_lbl;
    // End of variables declaration//GEN-END:variables

    private Color Color(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
